# Here the default values of the config are defined.
# But it is strongly recomendated to redifine while deploy in production.
# You may redifine it using os enirenment,
# for ex.: export SERVER_MODE=release 

loglevel: DEBUG

server:
  mode: "debug"  # Available values: "release" ,"debug" 
  port: "8080"

db:
  host: localhost
  port: "5432"
  name: someproject_db
  user: "some-user"
  password: some-password
  sslmode: disable
