# Here the default values of the config are defined.
# But it is strongly recomendated to redifine while deploy in production.
# You may redifine it using os enirenment,
# for ex.: export SERVER_MODE=release 

loglevel: DEBUG # Available values: INFO, DEBUG, ERROR 
access_token_ttl: 10 # minutes
refresh_token_ttl: 24 # hours
signing_key: sdFWlnxb13t&refgedgdfjsdgbv

# WARNING !!!
# Be careful with changing this parameter. You shoudl set it once at 
# the start of deploying, and after never change it. Changing after
# will result in clients not being able to login.
salt: sdfwevdweertgsadf 


server:
  mode: "debug"  # Available values: "release" ,"debug" 
  port: "8080"

db:
  host: localhost
  port: "5432"
  name: someproject_db
  user: "some-user"
  password: some-password
  sslmode: disable
